// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eGP.Registration.Persistance.Contexts;

namespace eGP.Registration.Persistance.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20190829122701_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("eGP.Registration.Persistance.EntityModels.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("date_created")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnName("date_modified")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Profile")
                        .HasColumnName("profile")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RootStructureId")
                        .HasColumnName("root_structure_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortName")
                        .HasColumnName("short_name")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StatusId");

                    b.Property<string>("Version")
                        .HasColumnName("version")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("organizations","registration");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "axy0{i}",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateCreated = new DateTime(2019, 8, 29, 12, 27, 0, 131, DateTimeKind.Utc).AddTicks(7904),
                            Name = "Ministry of ABC",
                            RootStructureId = new Guid("00000000-0000-0000-0000-000000000100"),
                            ShortName = "ABC",
                            StatusId = 0,
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "axy0{i}",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateCreated = new DateTime(2019, 8, 29, 12, 27, 0, 131, DateTimeKind.Utc).AddTicks(9520),
                            Name = "Ministry of ACB",
                            RootStructureId = new Guid("00000000-0000-0000-0000-000000000200"),
                            ShortName = "ACB",
                            StatusId = 0,
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "axy0{i}",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000030"),
                            DateCreated = new DateTime(2019, 8, 29, 12, 27, 0, 131, DateTimeKind.Utc).AddTicks(9556),
                            Name = "Ministry of BAC",
                            RootStructureId = new Guid("00000000-0000-0000-0000-000000000300"),
                            ShortName = "BAC",
                            StatusId = 0,
                            Version = "0.0.1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Code = "axy0{i}",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000040"),
                            DateCreated = new DateTime(2019, 8, 29, 12, 27, 0, 131, DateTimeKind.Utc).AddTicks(9579),
                            Name = "Ministry of BCA",
                            RootStructureId = new Guid("00000000-0000-0000-0000-000000000400"),
                            ShortName = "BCA",
                            StatusId = 0,
                            Version = "0.0.1"
                        });
                });

            modelBuilder.Entity("eGP.Registration.Persistance.Models.OrganizationStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<string>("Name");

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("ParentId");

                    b.Property<string>("Profile")
                        .HasColumnType("jsonb");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("OrganizationStructures");
                });

            modelBuilder.Entity("eGP.Registration.Persistance.Models.Placement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime?>("DateModified");

                    b.Property<Guid?>("ModifiedBy");

                    b.Property<Guid>("OrganizationId");

                    b.Property<Guid>("PersonnelId");

                    b.Property<Guid>("StructureId");

                    b.HasKey("Id");

                    b.ToTable("Placements");
                });
#pragma warning restore 612, 618
        }
    }
}
